### ISSUE TITLE
Investigar alternativas a MelonJS.

### ISSUE THREAD

**Issue by ealmansi** [lausuper/Robotica#10]
Ver si vale la pena usar una alternativa más sencilla.

**Comment by lausuper** [comment]
Me parece que ya no vale la pena esto. Si bien es complejo implementar algunas cosas, ya estamos en medio de la implementación y hacer un cambio sería perder lo ya hecho.

**Comment by ealmansi** [comment]
No vamos a cambiar melonjs, por lo menos para la v1.
