### ISSUE TITLE
Evitar que desaparezcan los bloques en blockly si se posicionan sobre el borde izquierdo.

### ISSUE THREAD

**Issue by ealmansi** [lausuper/Robotica#12]
Ideas: Auto-ajustar zoom si el conjunto de bloques se escapa del espacio blanco de blockly, Y/O hacer el bloque de motor vertical en vez de horizontal.

**Comment by jesiv** [comment]
Estuve viendo ardublockly y parece que es algo propio de blockly eliminar los bloques cuando se posicionan en la izquierda de determinada manera, entonces con auto-ajustar el zoom dicen de hacer los bloques más chicos si se están moviendo a la izquierda ?

**Comment by ealmansi** [comment]
Yo revisaría la idea de sacar esa funcionalidad. Con el nuevo layout no me pasa nunca de eliminar bloques sin querer, y lo uso bastante seguido para eliminar bloques a propósito.

**Comment by ealmansi** [comment]
o que vocês acham?

**Comment by jesiv** [comment]
Yo tampoco elimino bloques sin querer, los demás qué opinan ?

**Comment by ealmansi** [comment]
Quizás en vez de sacar esto, podríamos meter un botón de "Undo" para la última acción. Ya caería para la v2 seguro pero no es demasiado dificil de implementar.

**Comment by lausuper** [comment]
Los de APP Inventor estuvieron trabajando en esto:
https://docs.google.com/document/d/1cmXWw3KhlAEp6huOmvzW_wly7q1GuLuY7FKYay6KIEA/edit#heading=h.d8zqp714y1nx
https://github.com/dhchoi/appinventor-sources/commits/undo

**Comment by lausuper** [comment]
Me confundí, un botón de undo es lo que decían, la operación undo ya existe.

**Comment by ealmansi** [comment]
Si decidimos agregar el botón de undo, eso va en un nuevo issue. Cierro este con wont-fix.
