### ISSUE TITLE
Selección un subset didáctico de los bloques de lógica y control. Traducir.

### ISSUE THREAD

**Issue by ealmansi** [lausuper/Robotica#13]
Eliminar bloques innecesarios de los bloques default de control y lógica, y traducirlos al español.

**Comment by jesiv** [comment]
**Lógica**

quedan:
if then else
=, !=, <, >
and, or
true, false
not

no quedan:
null
test
if true
if false

**Secuencias**
no queda:
repeat x times

quedan:
repeat while-until
for
break out of loop

**Matemáticas**

quedan:
+, -, /, *
raíz, valor absoluto, ln..
par, impar, primo ..
change item by x
reminder of a / b
random integer

no quedan:
sen, con, tan
pi, e..
round, round up, round down
sum of list
constrain x low y high z
random fraction

Díganme qué les parece así los cambio.

Saludos!

**Comment by lausuper** [comment]
Coincido en que hay que eliminar:
-  test
- if true
- if false
- random fraction
- constrain x low y high z
- sum of list

Quedan:
- if then else
- =, !=, <, >
- and, or
- true, false
- not
- repeat while-until
- for
- break out of loop
- +, -, /, *
- raíz, valor absoluto, ln..
- par, impar, primo ..
- change item by x
- reminder of a / b
- random integer

De las que tengo dudas:
- par, impar, primo -> Cuándo las usarían?
- repeat x times -> Podría quedarse como una manera más fácil de aprender el for, además que si queremos hacer muchos fors simples, es más fácil como sintaxis.
- sen, con, tan
- pi, e..
Creo que pi, e, sen, cos, tan pueden usarse para calcular algún aspecto del movimiento del robot, pero no estoy seguro si lo usarían o no.

**Comment by jesiv** [comment]
de par, impar, primo tuve dudas, pero pensé que si tal vez usan el programa profes de secundario estaba bueno que hagan ejercicios un poco más complejos, pero tranquilamente pueden no estar.

estoy de acuerdo con repeat x times

el tema es que ya con darle velocidad a los motores de las ruedas pueden simular los movimientos del robot, igual para mi no resta que estén, en principio los podemos dejar y ver si se nos ocurre cuándo podrían usarlo

**Comment by jesiv** [comment]
y  round, round up, round down no son necesarias no ?

**Comment by sevita** [comment]
Para mi repeat x times, sen, con, tan, pi, e tienen que estar sí o sí. 

Con el round no estoy seguro, pero al haber división, yo lo dejaría

**Comment by jesiv** [comment]
ok, entonces ahora agrego round
