### ISSUE TITLE
Investigar cómo guardar y cargar código blockly.

### ISSUE THREAD

**Issue by ealmansi** [lausuper/Robotica#5]
Implementar solo si es sencillo. Buscar cómo hacer que el browser le muestre un popup de descarga de archivo al usuario, en lo posible con el contenido de una variable string desde javascript.

**Comment by ealmansi** [comment]
Voy a implementar esto cuando tenga un rato de tiempo. Encontré una forma de hacerlo funcar en todos los exploradores: http://stackoverflow.com/questions/18755750/saving-text-in-a-local-file-in-internet-explorer-10.

**Comment by ealmansi** [comment]
Ya está implementado en la branch build-system.

**Comment by lausuper** [comment]
Hiciste las dos cosas en el mismo branch? Cargar, guardar código y todo el build system? Podes incluir un readme de cómo usarlo?

**Comment by ealmansi** [comment]
Implementado en módulo CodeExport.
