### ISSUE TITLE
Arreglar censado de la pared izquierda

### ISSUE THREAD

**Issue by sevita** [lausuper/Robotica#59]
Ninguno de los 3 sensores detecta a la pared izquierda de los tableros.

**Comment by lausuper** [comment]
Qué sería un tablero? Un ejemplo? Cómo reproducirlo?

**Comment by sevita** [comment]
En cualquier mapa (no tablero, perdón) 

rueda izq: 10 rueda der: 0 tiempo: 2
rueda izq: 20 rueda der: 20 tiempo: 2

Si se coloca el debug, los sensores se mantienen en 50 al aproximarse al lado izquierdo del tablero
